bot_id를 self.client에서 자동으로 가져옴
koreanbots/py-sdk pull request #32
Opened 2021-09-18 06:18 UTC by Craphting

discord.py의 client가 지정된 경우,
해당 클라이언트에서 ID를 가져옵니다.

2021-09-18 08:33 UTC, kijk2869 requested changes

2021-09-18 08:33 UTC, kijk2869 commented on koreanbots/client.py
> +            bot_id = self.client.user.id
discord.Client의 user은 Optional입니다.

2021-09-18 15:52 UTC, Craphting commented on koreanbots/client.py
> +            bot_id = self.client.user.id
확인했습니다 :)

2021-09-18 17:43 UTC, SaidBySolo reviewed
이 PR은 생각좀 해봐야할거같아요.

2021-09-27 03:45 UTC, SaidBySolo commented
의존이되는 PR이라 코드가 broke 될수도있을것같아요.

2021-09-27 03:45 UTC, closed without merging