fix: 서버 수 업데이트 시 오류 핸들링
koreanbots/py-sdk pull request #46
Opened 2024-09-17 14:17 UTC by skinmaker1345

- 오류로 인해 서버 수 업데이트가 더 이상 진행되지 않을 수 있는 문제를 해결합니다.

2024-09-17 15:18 UTC, eunwoo1104 commented on koreanbots/http.py
>                      reset_limit_timestamp = int(response.headers["x-ratelimit-reset"])
생각해보니까 여기서도 KeyError가 발생할 소지가 있을 수 있지 않을까요? `x-ratelimit-reset` 헤더가 설정되지 않는 경우가 있는지 확인해야 할 것 같아요.

2024-09-17 15:48 UTC, SaidBySolo commented
아마도 cloudflare쪽에서 에러 반환되면 헤더가 안들어 갈거에요

2024-09-17 16:19 UTC, skinmaker1345 commented on koreanbots/http.py
>                      reset_limit_timestamp = int(response.headers["x-ratelimit-reset"])
둘 다 없거나 둘 다 있는 경우만 고려해도 괜찮을 거 같네요

2024-09-18 02:31 UTC, star0202 commented on koreanbots/http.py
> +                    or response.status == 429
```suggestion
                    response.status == 249
                    or remain_limit is not None
                    and int(remain_limit) == 0
```

2024-09-18 02:33 UTC, star0202 requested changes

2024-09-18 02:33 UTC, star0202 commented on koreanbots/http.py
> +                    or response.status == 429
```suggestion
                    response.status == 249
                    or remain_limit is not None
                    and int(remain_limit) == 0
```

2024-09-18 11:00 UTC, eunwoo1104 approved these changes

2024-09-18 11:00 UTC, merged