BREAKING CHANGE: support koreanbots v2
koreanbots/py-sdk pull request #6
Opened 2021-04-03 15:53 UTC by SaidBySolo

2021-04-03 16:23 UTC, wonderlandpark requested changes

2021-04-03 16:23 UTC, wonderlandpark commented on koreanbots/typing.py
> +]
Categories are added please check docs

Ref: https://beta.koreanbots.dev/developers/docs/엔드포인트/봇#category

2021-04-03 16:23 UTC, wonderlandpark commented on koreanbots/http.py
> +        await self.request("GET", "json", f"/bots/voted/{user_id}")
This would change, just leaving a comment for reminding

2021-04-03 16:37 UTC, kijk2869 requested changes

2021-04-03 16:37 UTC, kijk2869 commented on koreanbots/client.py
> +from koreanbots.decorator import strict_literal
Make it dynamic import

2021-04-03 16:37 UTC, kijk2869 commented on koreanbots/client.py
> +from koreanbots.errors import HTTPException
Make it dynamic import

2021-04-03 16:37 UTC, kijk2869 commented on koreanbots/client.py
> +        client: Optional[Type[discord.Client]],
client is not optional argument

2021-04-03 16:37 UTC, kijk2869 commented on koreanbots/client.py
> +                await self.guildcount(bot_id, total_guilds)
Should print or log the exception

2021-04-03 16:37 UTC, kijk2869 commented on koreanbots/client.py
> +        bot_id = (await self.client.application_info()).id  # type:ignore
Bot id will be loaded when ready

2021-04-03 16:37 UTC, kijk2869 commented on koreanbots/client.py
> +    async def guildcount(self, bot_id: int, total_guilds: int):
Add return type

2021-04-03 16:37 UTC, kijk2869 commented on koreanbots/client.py
> +    async def userinfo(self, user_id: int):
Add return type

2021-04-03 16:37 UTC, kijk2869 commented on koreanbots/client.py
> +    async def botinfo(self, bot_id: int):
Add return type

2021-04-03 16:37 UTC, kijk2869 commented on koreanbots/client.py
> +    ):
Add return type

2021-04-03 16:37 UTC, kijk2869 commented on koreanbots/decorator.py
> +from koreanbots.errors import AuthorizeError
Make it dynamic import

2021-04-03 16:37 UTC, kijk2869 commented on koreanbots/decorator.py
> +                elif recive_arg := kwargs.get(argument_name):
This library supports **3.6+**

https://github.com/koreanbots/py-sdk/blob/fbb421f1ab9d2dc36a0dbcdd90b58c25a09427f7/setup.py#L40

2021-04-03 16:37 UTC, kijk2869 commented on koreanbots/errors.py
> +error_mapping = {400: BadRequest, 403: Forbidden, 404: NotFound}
```suggestion
ERROR_MAPPING = {400: BadRequest, 403: Forbidden, 404: NotFound}
```

2021-04-03 16:37 UTC, kijk2869 commented on koreanbots/http.py
> +from koreanbots.errors import HTTPException, error_mapping
Make it dynamic import

2021-04-03 16:37 UTC, kijk2869 commented on koreanbots/http.py
> +        api_key: Optional[str],
This argument is optional but there is no default argument

2021-04-03 16:37 UTC, kijk2869 commented on koreanbots/client.py
> +        api_key: Optional[str],
This argument is optional but there is no default argument

2021-04-03 16:37 UTC, kijk2869 commented on koreanbots/client.py
> +        session: Optional[aiohttp.ClientSession],
This argument is optional but there is no default argument

2021-04-03 16:37 UTC, kijk2869 commented on koreanbots/client.py
> +    ) -> None:
Use typing.NoReturn

2021-04-03 16:37 UTC, kijk2869 commented on koreanbots/http.py
> +        return_method: Literal["json", "text", "read"],
I'm not suggesting this way.

2021-04-03 16:37 UTC, kijk2869 commented on koreanbots/http.py
> +                    raise error_mapping[response.status](
```suggestion
                if ERROR_MAPPING.get(response.status):
                    raise ERROR_MAPPING[response.status](
```

2021-04-03 16:37 UTC, kijk2869 commented on koreanbots/http.py
> +from koreanbots.errors import HTTPException, error_mapping
```suggestion
from koreanbots.errors import HTTPException, ERROR_MAPPING
```

2021-04-03 16:37 UTC, kijk2869 commented on koreanbots/http.py
> +    async def get_vote(self, user_id: int):
Add return type

2021-04-03 16:37 UTC, kijk2869 commented on koreanbots/http.py
> +    async def get_bot_info(self, bot_id: int):
Add return type

2021-04-03 16:37 UTC, kijk2869 commented on koreanbots/http.py
> +    async def request(
Apply strict literal

2021-04-03 16:37 UTC, kijk2869 commented on koreanbots/http.py
> +    async def post_update_bot_info(self, bot_id: int, total_guilds: int):
Add return type

2021-04-03 16:37 UTC, kijk2869 commented on koreanbots/http.py
> +    ):
Add return type

2021-04-03 16:37 UTC, kijk2869 commented on koreanbots/http.py
> +        await self.request("GET", "json", f"/widget/bots/{widget_type}/{bot_id}.svg")
Add a way to use png

2021-04-03 16:37 UTC, kijk2869 commented on koreanbots/client.py
> +        super().__init__(api_key, session=session)
Change the order

2021-04-04 16:28 UTC, SaidBySolo commented
TODO:
Refactor rate-limit handler

.pop -> .get

2021-04-05 02:04 UTC, wonderlandpark requested changes

2021-04-05 02:04 UTC, wonderlandpark commented on koreanbots/model.py
> +    def state(self) -> Optional[State]:
Not nullable
```suggestion
    def state(self) -> State:
```

2021-05-06 14:25 UTC, wonderlandpark commented
Needs to support vote check api
(Added to docs)
@SaidBySolo sa

2021-05-09 00:42 UTC, wonderlandpark requested changes

2021-05-09 00:42 UTC, wonderlandpark commented on koreanbots/typing.py
> +    "슬래시 명령어",
```suggestion
    "빗금 명령어",
```

2021-05-18 01:01 UTC, wonderlandpark commented
Will only support `svg` format for the widget.
Needs action for it. Should convert it to png, jpg, webp etc.

2021-05-23 02:15 UTC, zero734kr reviewed
I will review this PR later; just commenting to show this at my main page

2021-05-23 04:34 UTC, wonderlandpark commented
> I will review this PR later; just commenting to show this on my main page

Requsted review

2021-05-23 14:50 UTC, zero734kr requested changes

2021-05-23 14:50 UTC, zero734kr commented on koreanbots/decorator.py
> +                elif kwargs.get(argument_name):
```suggestion
                elif kwargs.get(argument_name) and kwargs[argument_name] not in literal_list:
```

2021-05-23 14:50 UTC, zero734kr commented on koreanbots/errors.py
> +class KoreanbotsExeption(Exception):
Typo here
```suggestion
class KoreanbotsException(Exception):
```

2021-05-23 14:50 UTC, zero734kr commented on koreanbots/errors.py
> +            self.error = message.get("message", "KoreanbotsExeption")
Typo

2021-05-31 03:28 UTC, wonderlandpark requested changes
Could you update this URL?
https://github.com/koreanbots/py-sdk/blob/5e148cdb8f522cf20dd4c83f828a34f1f14f3e57/setup.py#L28

2021-07-04 05:01 UTC, kijk2869 requested changes

2021-07-04 05:01 UTC, kijk2869 commented on setup.py
> -    },
Restore it with refreshed information

2021-07-04 05:01 UTC, kijk2869 commented on setup.py
> +version = '2.0.0'
Save version on __init__.py for version information to be accessible on inline code.

2021-07-04 05:30 UTC, SaidBySolo commented on koreanbots/abc.py
> +    def __init__(self, **response_data: Any) -> None:
Can't use kwarg in TypedDict

2021-07-04 05:35 UTC, SaidBySolo commented on koreanbots/model.py
> +    def __init__(self, **response_data: Any) -> None:
Can't use TypedDict in kwarg

2021-07-04 13:03 UTC, wonderlandpark approved these changes

2021-07-10 02:57 UTC, merged